[package]
name = "ingestion-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.14.2"
tonic-prost = "0.14.2"
tokio = {version = "1.47.1", features = ["full"]}
tokio-stream = "0.1.17"
dotenv = "0.15.0"
prost = "0.14.1"

[build-dependencies]
tonic-prost-build = "0.14.2"
